# Site settings
title:       CSSSR
author:      CSSSR
email:       vostok@example.com
description: CSSSR — веб-студия, предоставляющая frontend аутсорсинг. Мы верстаем из PSD в HTML и CSS. Вёрстка для сайтов, лэндингов и почтовых рассылок.
url:         http://blog.csssr.ru

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: csssr
stackoverflow_id:
twitter_username: csssr_dev
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
